image: registry.gitlab.com/ldy985/dotnetsdk_gitversion:dotnet

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .nuget/

stages:
- build
build:
  stage: build
  script:
    - dotnet build _build.csproj