image: mcr.microsoft.com/dotnet/sdk:5.0

cache:
  key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
  paths:
    - .nuget/

stages:
- build
build:
  stage: build
  script:
    - dotnet build _build.csproj